#!/bin/bash

if [ "$#" -ne 2 ]; then
  echo 'Usage: youtube-music <search term> <out dir>' >&2
  echo '' >&2
  echo 'Files are saved to the current directory.' >&2
  exit 1
fi

QUERY="$1"
OUT_DIR="$2"

if [ ! -d "$OUT_DIR" ]; then
  echo 'not a directory:' "$OUT_DIR" >&2
  exit 1
fi

ITUNES_SEARCH="https://itunes.apple.com/search?limit=200&term="
ITUNES_LOOKUP="https://itunes.apple.com/lookup?entity=song&id="
YOUTUBE_SEARCH="https://www.youtube.com/results?search_query="

search_and_prompt() {
  local response=$(curl -s $ITUNES_SEARCH$(urlescape "$QUERY"))
  local resultCount=$(echo "$response" | jq .resultCount)

  local seen=""
  for i in $(seq 0 $((resultCount-1)))
  do
    local result=$(echo "$response" | jq .results | jq .[$i])
    local albumName=$(echo "$result" | jq .collectionName)
    local artistName=$(echo "$result" | jq .artistName)
    local collectionId=$(echo "$result" | jq .collectionId)
    local hasSeen=0
    for item in $seen
    do
      if [ $item = $collectionId ]; then
        local hasSeen=1
      fi
    done
    if [ $hasSeen -eq 0 ]; then
      local seen="$seen $collectionId"
      echo -n "Download $albumName by $artistName? [y/n]: "
      read userInput
      if [ "$userInput" = "y" ]; then
        echo 'Downloading...'
        fetch_album $(echo "$result" | jq .collectionId) \
          "$(echo "$artistName" | jq -r .)" \
          "$(echo "$albumName" | jq -r .)"
      fi
    fi
  done
}

fetch_album() {
  local artistName="$2"
  local albumName="$3"
  local response=$(curl -s $ITUNES_LOOKUP$1)
  local resultCount=$(echo "$response" | jq .resultCount)
  for i in $(seq 0 $((resultCount-1)))
  do
    local result=$(echo "$response" | jq .results | jq .[$i])
    local songName=$(echo "$result" | jq -r .trackName)
    local trackNumber=$(echo "$result" | jq -r .trackNumber)
    if [ "$songName" = null ]; then
      continue
    fi
    local vidId=$(youtube_search "$songName by $artistName")
    fetch_song "$vidId" "$songName" "$artistName" "$albumName" "$trackNumber"
  done
}

fetch_song() {
  local cleanName=$(echo "$2" | tr '/' ':')
  local filename="$cleanName.mp3"
  echo "Fetching $filename ..."
  cd $OUT_DIR
  youtube-dl https://youtube.com/watch?v=$1 \
    --quiet --extract-audio --audio-format mp3 \
    --output "$cleanName.%(ext)s"
  id3v2 --song "$2" "$filename"
  id3v2 --artist "$3" "$filename"
  id3v2 --album "$4" "$filename"
  id3v2 --track "$5" "$filename"
  cd - >/dev/null
}

youtube_search() {
  curl -s $YOUTUBE_SEARCH$(urlescape "$1") |
    sed -E $'s/href/\\\n/g' | grep '/watch?' |
    sed -E 's/(^="\/watch\?v=|&amp;.*|" .*)//g' |
    head -n 1
}

urlescape() {
  echo "$1" | xxd -ps | tr $'\n' ' ' | sed -E 's/ //g' |
    sed -E 's/([0-9a-f][0-9a-f])/%\1/g'
}

search_and_prompt
